
spring:
  application:
    name: web-client
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sensors_data
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: myclient
            client-secret: Kni4WSixTM0xLVFlAdjCnBbc8FCgHfUB
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/myrealm
            user-name-attribute: preferred_username

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

#url rest api
application:
  config:
    sensors-url: http://localhost:8189/sensors
    gateway-service-url: http://localhost:8080

#format output log
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

keycloak:
  server-url: http://localhost:8180/auth
  realm: myrealm
  username: admin
  password: adminpass
server:
  port: 8188

